synthetic-package: false

# The files are generated into the path specified by `arb-dir`
arb-dir: lib/l10n/arb

# Template file for the localization strings
template-arb-file: app_en.arb

# Or, specifically provide an output path:
output-localization-file: app_localizations.dart

nullable-getter: false
