name: my-football-app
description: A Flutter app to manage football matches.

packages:
  - packages/**
  - tools/**

scripts:
  # DEV SCRIPTS
  # Run flutter code formatter and analyzer
  clean-code-win:
    description: Format code and run analyzer.
    run: powershell -ExecutionPolicy Bypass -File tools/analyze-and-format.ps1

  clean-code-sh:
    description: Format code and run analyzer.
    run: sh tools/analyze-and-format.sh

  # Remove unused branches in local git repository  
  remove-branches-win:
    description: Remove branches that are not in use.
    run: powershell -ExecutionPolicy Bypass -File tools/remove-branches.ps1

  remove-branches-sh:
    description: Remove branches that are not in use.
    run: sh tools/remove-branches.sh

  generate-l10n:
    description: Generate localization files.
    run: |
      echo "🌐 Generando archivos de localización..." && flutter gen-l10n
