name: my-football-app
description: A Flutter app to manage football matches.

packages:
  - packages/**
  - tools/**

scripts:
  clean-code:
    description: Format code and run analyzer.
    exec: "sh tools/format.sh && sh tools/analyze-and-format.sh"
  
  remove-branches:
    description: Remove branches that are not in use.
    exec: "sh tools/remove-branches.sh"

  generate-l10n:
    description: Generate localization files.
    run: |
      echo "🌐 Generando archivos de localización..." && flutter gen-l10n
