name: my-football-app
description: A Flutter app to manage football matches.

packages:
  - packages/**
  - tools/**

scripts:
  clean-code:
    description: Format code and run analyzer.
    run: |
      echo "🔧 Formateando código..."
      dart format --line-length 80 --set-exit-if-changed lib test

      echo "🔍 Ejecutando análisis estático..."
      flutter analyze lib test
  
  remove-branches:
    description: Remove branches that are not in use.
    run: |
      echo "🗑️  Eliminando ramas no utilizadas..."
      bash tools/remove-branches.sh
      
  generate-l10n:
    description: Generate localization files.
    run: |
      echo "🌐 Generando archivos de localización..."
      flutter gen-l10n
